import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Banner from "../components/Banner";
import CategoryPicker from "../components/CategoryPicker";
import FeaturedBlogs from "../components/FeaturedBlogs";
import FeaturedProducts from "../components/FeaturedProducts";
import { BannerDataObjType, BlogType, ProductType } from "../types/types";

type HomeProps = {
  bannerData: BannerDataObjType,
  products: ProductType[],
  blogs: BlogType[]
}

const Home: NextPage<HomeProps> = ({bannerData, products, blogs}) => {
  return (
    <>
      <Head>
        <title>Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner {...bannerData}/>

      <CategoryPicker />

      <FeaturedProducts products={products}/>

      <FeaturedBlogs blogs={blogs}/>
    </>
  );
};

export default Home;

export const getStaticProps:GetStaticProps = async () => {

  const [bannerDataRes, productsRes, blogsRes] = await Promise.all([
    fetch('http://localhost:5001/banner_content'),
    fetch('http://localhost:5001/products/?_limit=4'),
    fetch('http://localhost:5001/blogs/?_limit=3')
  ])

  const [bannerData, products, blogs] = await Promise.all([
    bannerDataRes.json(),
    productsRes.json(),
    blogsRes.json()

  ])

  return {
    props: {
      bannerData,
      products,
      blogs
    }
  }
}