import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import BlogItem from "../components/BlogItem";
import PageTitle from "../components/PageTitle";
import ProductItem from "../components/ProductItem";
import { BlogType, ProductType } from "../types/types";

type SearchPageProps = {
  products: ProductType[];
  blogs: BlogType[];
};

const Search: NextPage<SearchPageProps> = ({ products = [], blogs = [] }) => {
  return (
    <>
      <Head>
        <title>Store - Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTitle />

      <div className="bg0 m-t-23 p-b-140 mt-5">
        <div className="container">
          {/* blogs  */}
          <>
            <h2 className="mb-5">Blogs</h2>
            <div className="row isotope-grid">
              {/* blog skeleton - search result */}
              {blogs.length > 0
                ? blogs.map((blog) => {
                    return (
                      <div key={blog.id} className="col-4">
                        {<BlogItem {...blog} />}
                      </div>
                    );
                  })
                : "No Results"}
            </div>
          </>

          {/* products */}
          <>
            <h2 className="mb-5">Products</h2>
            <div className="row isotope-grid">
              {products.length > 0
                ? products.map((product) => (
                    <ProductItem key={product.id} {...product} />
                  ))
                : "There Are No Such Products"}
            </div>
          </>
        </div>
      </div>
    </>
  );
};

export default Search;

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  const searchQuery = query.q as string;

  try {
    const [blogsRes, productsRes] = await Promise.all([
      fetch(`http://localhost:5001/blogs?q=${searchQuery}`),
      fetch(`http://localhost:5001/products?q=${searchQuery}`),
    ]);

    const [blogs, products] = await Promise.all([
      blogsRes.json(),
      productsRes.json(),
    ]);

    return {
      props: {
        products,
        blogs,
      },
    };
  } catch (err) {
    return {
      notFound: true,
    };
  }
};
